repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.7.4
      hooks:
          - id: ruff
            args: [ --fix ]
          - id: ruff-format
            stages: [commit]
default_install_hook_types: [pre-commit, pre-push]
default_stages: [commit, push]
